---
title: "analysis"
author: "Emil Hvitfeldt"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r, echo=FALSE}
drake::readd(islands_variability_chart)
```

```{r, echo=FALSE}
drake::readd(genes_variability_chart)
```

```{r, echo=FALSE}
drake::readd(promoters_variability_chart)
```

```{r, echo=FALSE}
drake::readd(enhancers_variability_chart)
```

```{r, echo=FALSE}
drake::readd(list_a_variability_chart)
```

```{r, echo=FALSE}
drake::readd(list_b_variability_chart)
```

## Normalizing information

The data have been normalized according to values found in island regions.
Sufficient statistics for normalization is found in this table

```{r, echo=FALSE}
scaler_recipe <- drake::readd(scaler_recipe)

tidy(scaler_recipe$steps[[1]]) %>%
  select(-id) %>%
  mutate(value = round(value, 4)) %>%
  pivot_wider(names_from = statistic, values_from = value) %>%
  kable()
```
